CREATE TABLE `USERS` (
	`USER_ID`	BIGINT	NOT NULL,
	`LOGIN_ID`	VARCHAR(255)	NOT NULL,
	`PASSWORD`	VARCHAR(255)	NOT NULL,
	`NICKNAME`	VARCHAR(255)	NOT NULL,
	`AGE`	INT	NOT NULL,
	`GENDER`	VARCHAR(255)	NOT NULL,
	`PROFILE_IMAGE`	VARCHAR(255)	NULL
);

CREATE TABLE `CAKE_STORES` (
	`STORE_ID`	BIGINT	NOT NULL,
	`STORE_NAME`	VARCHAR(255)	NOT NULL,
	`STORE_SCORE`	INT	NULL,
	`STORE_TIME`	VARCHAR(255)	NULL,
	`STORE_PHONENUMBER`	VARCHAR(255)	NULL,
	`STORE_INTRODUCE`	VARCHAR(255)	NULL,
	`LATITUDE`	DOUBLE	NOT NULL,
	`LONGITUDE`	DOUBLE	NOT NULL,
	`STORE_IMAGE`	VARCHAR(255)	NULL
);

CREATE TABLE `LIKES` (
	`LIKE_ID`	BIGINT	NOT NULL,
	`STORE_ID`	BIGINT	NOT NULL,
	`USER_ID`	BIGINT	NOT NULL,
	`LIKE_YN`	VARCHAR(1)	NOT NULL
);

CREATE TABLE `HASHTAGS` (
	`HASHTAG_ID`	BIGINT	NOT NULL,
	`STORE_ID`	BIGINT	NOT NULL,
	`NAME`	VARCHAR(255)	NULL
);

CREATE TABLE `RESERVATIONS` (
	`RESERVATION_ID`	BIGINT	NOT NULL,
	`USER_ID`	BIGINT	NOT NULL,
	`STORE_ID`	BIGINT	NOT NULL,
	`RESERVATION_DATE`	DATETIME	NOT NULL,
	`RESERVATION_IMAGE`	VARCHAR(255)	NULL,
	`RESERVATION_DETAIL`	VARCHAR(255)	NULL
);

CREATE TABLE `REVIEWS` (
	`REVIEW_ID`	BIGINT	NOT NULL,
	`STORE_ID`	BIGINT	NOT NULL,
	`CONTENT`	VARCHAR(255)	NULL
);

ALTER TABLE `USERS` ADD CONSTRAINT `PK_USERS` PRIMARY KEY (
	`USER_ID`
);

ALTER TABLE `CAKE_STORES` ADD CONSTRAINT `PK_CAKE_STORES` PRIMARY KEY (
	`STORE_ID`
);

ALTER TABLE `LIKES` ADD CONSTRAINT `PK_LIKES` PRIMARY KEY (
	`LIKE_ID`
);

ALTER TABLE `HASHTAGS` ADD CONSTRAINT `PK_HASHTAGS` PRIMARY KEY (
	`HASHTAG_ID`
);

ALTER TABLE `RESERVATIONS` ADD CONSTRAINT `PK_RESERVATIONS` PRIMARY KEY (
	`RESERVATION_ID`
);

ALTER TABLE `REVIEWS` ADD CONSTRAINT `PK_REVIEWS` PRIMARY KEY (
	`REVIEW_ID`
);

ALTER TABLE `LIKES` ADD CONSTRAINT `FK_CAKE_STORES_TO_LIKES_1` FOREIGN KEY (
	`STORE_ID`
)
REFERENCES `CAKE_STORES` (
	`STORE_ID`
);

ALTER TABLE `LIKES` ADD CONSTRAINT `FK_USERS_TO_LIKES_1` FOREIGN KEY (
	`USER_ID`
)
REFERENCES `USERS` (
	`USER_ID`
);

ALTER TABLE `HASHTAGS` ADD CONSTRAINT `FK_CAKE_STORES_TO_HASHTAGS_1` FOREIGN KEY (
	`STORE_ID`
)
REFERENCES `CAKE_STORES` (
	`STORE_ID`
);

ALTER TABLE `RESERVATIONS` ADD CONSTRAINT `FK_USERS_TO_RESERVATIONS_1` FOREIGN KEY (
	`USER_ID`
)
REFERENCES `USERS` (
	`USER_ID`
);

ALTER TABLE `RESERVATIONS` ADD CONSTRAINT `FK_CAKE_STORES_TO_RESERVATIONS_1` FOREIGN KEY (
	`STORE_ID`
)
REFERENCES `CAKE_STORES` (
	`STORE_ID`
);

ALTER TABLE `REVIEWS` ADD CONSTRAINT `FK_CAKE_STORES_TO_REVIEWS_1` FOREIGN KEY (
	`STORE_ID`
)
REFERENCES `CAKE_STORES` (
	`STORE_ID`
);

